kind: helm-release
apiVersion: 1.0
build:
  context: .
  dockerfile: Dockerfile
install:
  chart: charts/amp
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
  set:
    image:
      tag: $(tag)
      pullPolicy: Never
    disableProbes: true
    ingress:
      hosts:
      # This expands to [space.s.]amp.<guid>.<region>.aksapp.io
      - $(spacePrefix)amp$(hostSuffix)
configurations:
  develop:
    build:
      useGitIgnore: true
    container:
      syncTarget: /app
      sync:
      - "!**/package.json"
      iterate:
        processesToKill: [node]
  develop.attach:
    build:
      useGitIgnore: true
    container:
      syncTarget: /app
      sync:
      - "!**/package.json"