kind: Pod
apiVersion: v1
metadata:
  name: api
  labels:
    app: api

spec:
  containers:
    - name: api
      image: inklin/api:latest
      env:
      - name: MONGODB
        value: "mongodb://inklin:EsgG40AL0aCdIzD087RhzG9IdKBnb6bP2e4iEnPY2vYrxRloWVhH3SqorPphndPdBHEfWAiwLH79D64WaiQ5fg==@inklin.documents.azure.com:10255/visualise_ethereum?ssl=true&replicaSet=globaldb"
      ports:
      - containerPort: 80

